# Generated by Django 2.0.2 on 2018-03-06 21:52

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('attached_piece', models.FileField(upload_to='documents/')),
            ],
        ),
        migrations.CreateModel(
            name='Salaried',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('cin_code', models.CharField(max_length=10)),
                ('birth_day', models.DateField()),
                ('hire_day', models.DateField()),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('cnss_code', models.CharField(max_length=30)),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('bu', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bu.BU')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='document',
            name='salaried',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salaried.Salaried'),
        ),
    ]
