# Generated by Django 2.0.2 on 2018-03-10 08:06

import django.core.validators
from django.db import migrations, models
import salaried.models


class Migration(migrations.Migration):

    dependencies = [
        ('salaried', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='attached_piece',
            field=models.FileField(upload_to=salaried.models.Document.user_directory_path, validators=[django.core.validators.FileExtensionValidator(['pdf', 'doc', 'docx', 'jpg', 'jpeg', 'png'])]),
        ),
        migrations.AlterField(
            model_name='document',
            name='label',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='salaried',
            name='cin_code',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='salaried',
            name='cnss_code',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
